server:
  port: 38030
  servlet:
    context-path: /jfc-shop
  #logging:
  #  level:
  #    root: INFO
  config: classpath:logback.xml
white_list: /jfc-shop/suser/getVtoken,/jfc-shop/suser/getLoginCode,/jfc-shop/suser/login,/jfc-shop/wuser/isLogin,/jfc-shop/wuser/login,/jfc-shop/weixin/getPaySuccess,/jfc-shop/order/orderPaySuccess,/jfc-shop/cmn/sendMsgInfo,/jfc-shop/orderPay/orderPaySuccess,/jfc-shop/orderPay/getMyPaySuccess,

#ribbon:
#  ConnectTimeout: 60000
#  ReadTimeout: 60000
---
img_url: http://static.vip.cnhtol.net/

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka
spring:
  application:
    name: jfc-shop #服务名称--调用的时候根据名称来调用该服务的方法
---
spring:
  datasource:
    readSize: 1
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      url: jdbc:mysql://39.100.67.248:3306/qiyue?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: jack
      password: 6yhn^YHN
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat,wall
      initialSize: 5
      maxActive: 200
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      useGlobalDataSourceStat: true
      validationQuery: SELECT 1 FROM DUAL
    slave:
      url: jdbc:mysql://39.100.67.248:3306/qiyue?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: jack
      password: 6yhn^YHN
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat,wall
      initialSize: 5
      maxActive: 200
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      useGlobalDataSourceStat: true
      validationQuery: SELECT 1 FROM DUAL
  messages:
    encoding: UTF-8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
---
mybatis:
  config-location: classpath:mybatis.cfg.xml    #  mybatis主配置文件所在路径
  type-aliases-package: com.jfc.bean
  mapper-locations: classpath:mapper/*/*.xml
mapper:
  not-empty: false
  identity: MYSQL

---
spring:
  redis:
    host: 219.235.6.205
    port: 6379                  #password: fa$17p%w0%nsQJz2    自助重启平台：http://www.gotonets.com/gotonets/    您的用户名为：900161526    初始密码为：121212
    password: foo123456bared
    timeout: 5000
    lettuce:
      pool:
        max-active: 500
        max-idle: 200
        min-idle: 20
        max-wait: 500
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
---